name: Release

on: push

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Temurin JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build (installDist)
        run: ./gradlew --no-daemon clean :installDist

      - name: Debug
        run: ls -al

      - name: Upload installDist artifact
        uses: actions/upload-artifact@v4
        with:
          name: engine-install
          path: build/install/engine/**  # <- 여기 bin/, lib/ 다 포함됨
